### ISSUE TITLE
project URL needs to be fixed

### ISSUE THREAD

**Issue by sarbbottam** [code-kotis/pwa-codelabs#3]
Instead of https://github-cards.surge.sh/ I guess it should be https://pwa.tips/codelabs/
<img width="560" alt="screen shot 2016-11-10 at 1 50 14 pm" src="https://cloud.githubusercontent.com/assets/949380/20200462/3755918c-a766-11e6-84fb-b21fe944c34b.png">

**Comment by hemanth** [comment]
Thanks, fixed.
